version: '2.1'

services:
  
  raven-db: 
    image: pizycki/ravendb
    ports:
      - "8080:8080"
    networks:
      #- app-net
      app-net:
        ipv4_address: 172.29.4.11

  message-queue:
    image: nats:windowsservercore
    ports:
      - "4222:4222"
    networks:
      #- app-net
      app-net:
        ipv4_address: 172.29.4.12

  product-launch-web:
    image: sixeyed/msdn-web-app:v2
    ports:
      - "80:80"
    depends_on:
      - message-queue
    networks:
      #- app-net
      app-net:
        ipv4_address: 172.29.4.13

  save-prospect-handler:
    image: sixeyed/msdn-save-handler:v2
    depends_on:
      - raven-db
      - message-queue
    networks:
      #- app-net
      app-net:
        ipv4_address: 172.29.4.14

networks:
  app-net:
    external:
      name: nat