version: '2.1'

services:
  
  sql-server:
    image: microsoft/mssql-server-windows-express
    ports:
      - "1433:1433"
    environment: 
      - ACCEPT_EULA=Y
      - sa_password=MSDNm4g4z!n3
    networks:
      - app-net

  message-queue:
    image: nats:windowsservercore
    ports:
      - "4222:4222"
    networks:
      - app-net

  product-launch-web:
    image: sixeyed/msdn-web-app:v2
    ports:
      - "80:80"
    depends_on:
      - sql-server
      - message-queue
    networks:
      - app-net

  save-prospect-handler:
    image: sixeyed/msdn-save-handler:v2
    depends_on:
      - sql-server
      - message-queue
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat